# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bookkeeper/module/module.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.app.v1alpha1 import module_pb2 as cosmos_dot_app_dot_v1alpha1_dot_module__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(inference/bookkeeper/module/module.proto\x12\x1binference.bookkeeper.module\x1a cosmos/app/v1alpha1/module.proto\"\xc3\x01\n\x06Module\x12\x1c\n\tauthority\x18\x01 \x01(\tR\tauthority\x12!\n\x0c\x64ouble_entry\x18\x02 \x01(\x08R\x0b\x64oubleEntry\x12!\n\x0csimple_entry\x18\x03 \x01(\x08R\x0bsimpleEntry\x12\x1b\n\tlog_level\x18\x04 \x01(\tR\x08logLevel:8\xba\xc0\x96\xda\x01\x32\n0github.com/productscience/inference/x/bookkeeperb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bookkeeper.module.module_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODULE']._options = None
  _globals['_MODULE']._serialized_options = b'\272\300\226\332\0012\n0github.com/productscience/inference/x/bookkeeper'
  _globals['_MODULE']._serialized_start=108
  _globals['_MODULE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
