# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bls/genesis.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.bls import params_pb2 as inference_dot_bls_dot_params__pb2
from inference.bls import types_pb2 as inference_dot_bls_dot_types__pb2
from inference.bls import threshold_signing_pb2 as inference_dot_bls_dot_threshold__signing__pb2
from inference.bls import group_validation_pb2 as inference_dot_bls_dot_group__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1binference/bls/genesis.proto\x12\rinference.bls\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1ainference/bls/params.proto\x1a\x19inference/bls/types.proto\x1a%inference/bls/threshold_signing.proto\x1a$inference/bls/group_validation.proto\"\xaf\x03\n\x0cGenesisState\x12\x38\n\x06params\x18\x01 \x01(\x0b\x32\x15.inference.bls.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12&\n\x0f\x61\x63tive_epoch_id\x18\x02 \x01(\x04R\ractiveEpochId\x12\x37\n\x18\x63urrent_signing_epoch_id\x18\x06 \x01(\x04R\x15\x63urrentSigningEpochId\x12\x45\n\rbls_data_list\x18\x03 \x03(\x0b\x32\x1b.inference.bls.EpochBLSDataB\x04\xc8\xde\x1f\x00R\x0b\x62lsDataList\x12W\n\x10signing_requests\x18\x04 \x03(\x0b\x32&.inference.bls.ThresholdSigningRequestB\x04\xc8\xde\x1f\x00R\x0fsigningRequests\x12\x64\n\x17group_validation_states\x18\x05 \x03(\x0b\x32&.inference.bls.GroupKeyValidationStateB\x04\xc8\xde\x1f\x00R\x15groupValidationStatesB1Z/github.com/productscience/inference/x/bls/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bls.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/productscience/inference/x/bls/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['bls_data_list']._options = None
  _globals['_GENESISSTATE'].fields_by_name['bls_data_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['signing_requests']._options = None
  _globals['_GENESISSTATE'].fields_by_name['signing_requests']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['group_validation_states']._options = None
  _globals['_GENESISSTATE'].fields_by_name['group_validation_states']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=220
  _globals['_GENESISSTATE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
