# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bls/group_validation.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.bls import params_pb2 as inference_dot_bls_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$inference/bls/group_validation.proto\x12\rinference.bls\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1ainference/bls/params.proto\"\xef\x02\n\x17GroupKeyValidationState\x12 \n\x0cnew_epoch_id\x18\x01 \x01(\x04R\nnewEpochId\x12*\n\x11previous_epoch_id\x18\x02 \x01(\x04R\x0fpreviousEpochId\x12?\n\x06status\x18\x03 \x01(\x0e\x32\'.inference.bls.GroupKeyValidationStatusR\x06status\x12T\n\x12partial_signatures\x18\x04 \x03(\x0b\x32\x1f.inference.bls.PartialSignatureB\x04\xc8\xde\x1f\x00R\x11partialSignatures\x12\'\n\x0f\x66inal_signature\x18\x05 \x01(\x0cR\x0e\x66inalSignature\x12!\n\x0cmessage_hash\x18\x06 \x01(\x0cR\x0bmessageHash\x12#\n\rslots_covered\x18\x07 \x01(\rR\x0cslotsCovered*\xaf\x01\n\x18GroupKeyValidationStatus\x12\x35\n1GROUP_KEY_VALIDATION_STATUS_COLLECTING_SIGNATURES\x10\x00\x12)\n%GROUP_KEY_VALIDATION_STATUS_VALIDATED\x10\x01\x12\x31\n-GROUP_KEY_VALIDATION_STATUS_VALIDATION_FAILED\x10\x02\x42\x31Z/github.com/productscience/inference/x/bls/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bls.group_validation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/productscience/inference/x/bls/types'
  _globals['_GROUPKEYVALIDATIONSTATE'].fields_by_name['partial_signatures']._options = None
  _globals['_GROUPKEYVALIDATIONSTATE'].fields_by_name['partial_signatures']._serialized_options = b'\310\336\037\000'
  _globals['_GROUPKEYVALIDATIONSTATUS']._serialized_start=495
  _globals['_GROUPKEYVALIDATIONSTATUS']._serialized_end=670
  _globals['_GROUPKEYVALIDATIONSTATE']._serialized_start=125
  _globals['_GROUPKEYVALIDATIONSTATE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
