# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bls/params.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ainference/bls/params.proto\x12\rinference.bls\x1a\x11\x61mino/amino.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"\xf9\x03\n\x06Params\x12\"\n\ri_total_slots\x18\x01 \x01(\rR\x0biTotalSlots\x12\x31\n\x15t_slots_degree_offset\x18\x02 \x01(\rR\x12tSlotsDegreeOffset\x12\x41\n\x1d\x64\x65\x61ling_phase_duration_blocks\x18\x03 \x01(\x03R\x1a\x64\x65\x61lingPhaseDurationBlocks\x12K\n\"verification_phase_duration_blocks\x18\x04 \x01(\x03R\x1fverificationPhaseDurationBlocks\x12\x36\n\x17signing_deadline_blocks\x18\x05 \x01(\x03R\x15signingDeadlineBlocks\x12\x41\n\x1d\x64ispute_phase_duration_blocks\x18\x06 \x01(\x03R\x1a\x64isputePhaseDurationBlocks\x12:\n\x19\x63ompleted_fallback_blocks\x18\x07 \x01(\x03R\x17\x63ompletedFallbackBlocks\x12\x30\n\x14max_signing_attempts\x18\x08 \x01(\rR\x12maxSigningAttempts:\x1f\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x16inference/x/bls/Params\"\x9e\x01\n\x10PartialSignature\x12I\n\x13participant_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x12participantAddress\x12!\n\x0cslot_indices\x18\x02 \x03(\rR\x0bslotIndices\x12\x1c\n\tsignature\x18\x03 \x01(\x0cR\tsignatureB1Z/github.com/productscience/inference/x/bls/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bls.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/productscience/inference/x/bls/types'
  _globals['_PARAMS']._options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\026inference/x/bls/Params'
  _globals['_PARTIALSIGNATURE'].fields_by_name['participant_address']._options = None
  _globals['_PARTIALSIGNATURE'].fields_by_name['participant_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_PARAMS']._serialized_start=114
  _globals['_PARAMS']._serialized_end=619
  _globals['_PARTIALSIGNATURE']._serialized_start=622
  _globals['_PARTIALSIGNATURE']._serialized_end=780
# @@protoc_insertion_point(module_scope)
