# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bls/threshold_signing.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.bls import params_pb2 as inference_dot_bls_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%inference/bls/threshold_signing.proto\x12\rinference.bls\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1ainference/bls/params.proto\"\x85\x01\n\x0bSigningData\x12(\n\x10\x63urrent_epoch_id\x18\x01 \x01(\x04R\x0e\x63urrentEpochId\x12\x19\n\x08\x63hain_id\x18\x02 \x01(\x0cR\x07\x63hainId\x12\x1d\n\nrequest_id\x18\x03 \x01(\x0cR\trequestId\x12\x12\n\x04\x64\x61ta\x18\x04 \x03(\x0cR\x04\x64\x61ta\"\x95\x04\n\x17ThresholdSigningRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\x0cR\trequestId\x12(\n\x10\x63urrent_epoch_id\x18\x02 \x01(\x04R\x0e\x63urrentEpochId\x12\x19\n\x08\x63hain_id\x18\x03 \x01(\x0cR\x07\x63hainId\x12\x12\n\x04\x64\x61ta\x18\x04 \x03(\x0cR\x04\x64\x61ta\x12!\n\x0c\x65ncoded_data\x18\x05 \x01(\x0cR\x0b\x65ncodedData\x12!\n\x0cmessage_hash\x18\x06 \x01(\x0cR\x0bmessageHash\x12=\n\x06status\x18\x07 \x01(\x0e\x32%.inference.bls.ThresholdSigningStatusR\x06status\x12T\n\x12partial_signatures\x18\x08 \x03(\x0b\x32\x1f.inference.bls.PartialSignatureB\x04\xc8\xde\x1f\x00R\x11partialSignatures\x12\'\n\x0f\x66inal_signature\x18\t \x01(\x0cR\x0e\x66inalSignature\x12\x30\n\x14\x63reated_block_height\x18\n \x01(\x03R\x12\x63reatedBlockHeight\x12\x32\n\x15\x64\x65\x61\x64line_block_height\x18\x0b \x01(\x03R\x13\x64\x65\x61\x64lineBlockHeight\x12\x18\n\x07\x61ttempt\x18\x0c \x01(\rR\x07\x61ttempt*\xbd\x02\n\x16ThresholdSigningStatus\x12&\n\"THRESHOLD_SIGNING_STATUS_UNDEFINED\x10\x00\x12,\n(THRESHOLD_SIGNING_STATUS_PENDING_SIGNING\x10\x01\x12\x32\n.THRESHOLD_SIGNING_STATUS_COLLECTING_SIGNATURES\x10\x02\x12&\n\"THRESHOLD_SIGNING_STATUS_COMPLETED\x10\x03\x12#\n\x1fTHRESHOLD_SIGNING_STATUS_FAILED\x10\x04\x12$\n THRESHOLD_SIGNING_STATUS_EXPIRED\x10\x05\x12&\n\"THRESHOLD_SIGNING_STATUS_CANCELLED\x10\x06\x42\x31Z/github.com/productscience/inference/x/bls/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bls.threshold_signing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/productscience/inference/x/bls/types'
  _globals['_THRESHOLDSIGNINGREQUEST'].fields_by_name['partial_signatures']._options = None
  _globals['_THRESHOLDSIGNINGREQUEST'].fields_by_name['partial_signatures']._serialized_options = b'\310\336\037\000'
  _globals['_THRESHOLDSIGNINGSTATUS']._serialized_start=798
  _globals['_THRESHOLDSIGNINGSTATUS']._serialized_end=1115
  _globals['_SIGNINGDATA']._serialized_start=126
  _globals['_SIGNINGDATA']._serialized_end=259
  _globals['_THRESHOLDSIGNINGREQUEST']._serialized_start=262
  _globals['_THRESHOLDSIGNINGREQUEST']._serialized_end=795
# @@protoc_insertion_point(module_scope)
