# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/activeparticipants.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from inference.inference import random_seed_pb2 as inference_dot_inference_dot_random__seed__pb2
from inference.inference import epoch_group_data_pb2 as inference_dot_inference_dot_epoch__group__data__pb2
from inference.inference import poc_delegation_pb2 as inference_dot_inference_dot_poc__delegation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,inference/inference/activeparticipants.proto\x12\x13inference.inference\x1a%inference/inference/random_seed.proto\x1a*inference/inference/epoch_group_data.proto\x1a(inference/inference/poc_delegation.proto\"J\n\x0cModelMLNodes\x12:\n\x08ml_nodes\x18\x01 \x03(\x0b\x32\x1f.inference.inference.MLNodeInfoR\x07mlNodes\"\xc3\x02\n\x12\x41\x63tiveParticipants\x12J\n\x0cparticipants\x18\x01 \x03(\x0b\x32&.inference.inference.ActiveParticipantR\x0cparticipants\x12$\n\x0e\x65poch_group_id\x18\x02 \x01(\x04R\x0c\x65pochGroupId\x12\x33\n\x16poc_start_block_height\x18\x03 \x01(\x03R\x13pocStartBlockHeight\x12\x34\n\x16\x65\x66\x66\x65\x63tive_block_height\x18\x04 \x01(\x03R\x14\x65\x66\x66\x65\x63tiveBlockHeight\x12\x35\n\x17\x63reated_at_block_height\x18\x05 \x01(\x03R\x14\x63reatedAtBlockHeight\x12\x19\n\x08\x65poch_id\x18\x06 \x01(\x04R\x07\x65pochId\"\xe2\x02\n\x11\x41\x63tiveParticipant\x12\x14\n\x05index\x18\x01 \x01(\tR\x05index\x12#\n\rvalidator_key\x18\x02 \x01(\tR\x0cvalidatorKey\x12\x16\n\x06weight\x18\x03 \x01(\x03R\x06weight\x12#\n\rinference_url\x18\x04 \x01(\tR\x0cinferenceUrl\x12\x16\n\x06models\x18\x05 \x03(\tR\x06models\x12\x33\n\x04seed\x18\x06 \x01(\x0b\x32\x1f.inference.inference.RandomSeedR\x04seed\x12<\n\x08ml_nodes\x18\x07 \x03(\x0b\x32!.inference.inference.ModelMLNodesR\x07mlNodes\x12J\n\rvoting_powers\x18\x08 \x03(\x0b\x32%.inference.inference.ModelVotingPowerR\x0cvotingPowersB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.activeparticipants_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_MODELMLNODES']._serialized_start=194
  _globals['_MODELMLNODES']._serialized_end=268
  _globals['_ACTIVEPARTICIPANTS']._serialized_start=271
  _globals['_ACTIVEPARTICIPANTS']._serialized_end=594
  _globals['_ACTIVEPARTICIPANT']._serialized_start=597
  _globals['_ACTIVEPARTICIPANT']._serialized_end=951
# @@protoc_insertion_point(module_scope)
