# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/confirmation_poc_event.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0inference/inference/confirmation_poc_event.proto\x12\x13inference.inference\"\xad\x02\n\x14\x43onfirmationPoCEvent\x12\x1f\n\x0b\x65poch_index\x18\x01 \x01(\x04R\nepochIndex\x12%\n\x0e\x65vent_sequence\x18\x02 \x01(\x04R\reventSequence\x12%\n\x0etrigger_height\x18\x03 \x01(\x03R\rtriggerHeight\x12\x36\n\x17generation_start_height\x18\x04 \x01(\x03R\x15generationStartHeight\x12?\n\x05phase\x18\x08 \x01(\x0e\x32).inference.inference.ConfirmationPoCPhaseR\x05phase\x12-\n\x13poc_seed_block_hash\x18\t \x01(\tR\x10pocSeedBlockHash*\xba\x01\n\x14\x43onfirmationPoCPhase\x12\x1d\n\x19\x43ONFIRMATION_POC_INACTIVE\x10\x00\x12!\n\x1d\x43ONFIRMATION_POC_GRACE_PERIOD\x10\x01\x12\x1f\n\x1b\x43ONFIRMATION_POC_GENERATION\x10\x02\x12\x1f\n\x1b\x43ONFIRMATION_POC_VALIDATION\x10\x03\x12\x1e\n\x1a\x43ONFIRMATION_POC_COMPLETED\x10\x04\x42\x37Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.confirmation_poc_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_CONFIRMATIONPOCPHASE']._serialized_start=378
  _globals['_CONFIRMATIONPOCPHASE']._serialized_end=564
  _globals['_CONFIRMATIONPOCEVENT']._serialized_start=74
  _globals['_CONFIRMATIONPOCEVENT']._serialized_end=375
# @@protoc_insertion_point(module_scope)
