# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/devshard_settlement.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-inference/inference/devshard_settlement.proto\x12\x13inference.inference\"\xdf\x01\n\x16\x44\x65vshardHostStatsProto\x12\x17\n\x07slot_id\x18\x01 \x01(\rR\x06slotId\x12\x16\n\x06missed\x18\x02 \x01(\rR\x06missed\x12\x18\n\x07invalid\x18\x03 \x01(\rR\x07invalid\x12\x12\n\x04\x63ost\x18\x04 \x01(\x04R\x04\x63ost\x12\x31\n\x14required_validations\x18\x05 \x01(\rR\x13requiredValidations\x12\x33\n\x15\x63ompleted_validations\x18\x06 \x01(\rR\x14\x63ompletedValidations\"b\n\x19\x44\x65vshardHostStatsMapProto\x12\x45\n\x07\x65ntries\x18\x01 \x03(\x0b\x32+.inference.inference.DevshardHostStatsProtoR\x07\x65ntries\"q\n\x1d\x44\x65vshardStateSignatureContent\x12\x1d\n\nstate_root\x18\x01 \x01(\x0cR\tstateRoot\x12\x1b\n\tescrow_id\x18\x02 \x01(\tR\x08\x65scrowId\x12\x14\n\x05nonce\x18\x03 \x01(\x04R\x05nonceB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.devshard_settlement_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_DEVSHARDHOSTSTATSPROTO']._serialized_start=71
  _globals['_DEVSHARDHOSTSTATSPROTO']._serialized_end=294
  _globals['_DEVSHARDHOSTSTATSMAPPROTO']._serialized_start=296
  _globals['_DEVSHARDHOSTSTATSMAPPROTO']._serialized_end=394
  _globals['_DEVSHARDSTATESIGNATURECONTENT']._serialized_start=396
  _globals['_DEVSHARDSTATESIGNATURECONTENT']._serialized_end=509
# @@protoc_insertion_point(module_scope)
