# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/epoch_performance_summary.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3inference/inference/epoch_performance_summary.proto\x12\x13inference.inference\"\xa4\x03\n\x17\x45pochPerformanceSummary\x12\x1f\n\x0b\x65poch_index\x18\x01 \x01(\x04R\nepochIndex\x12%\n\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\'\n\x0finference_count\x18\x03 \x01(\x04R\x0einferenceCount\x12\'\n\x0fmissed_requests\x18\x04 \x01(\x04R\x0emissedRequests\x12!\n\x0c\x65\x61rned_coins\x18\x05 \x01(\x04R\x0b\x65\x61rnedCoins\x12%\n\x0erewarded_coins\x18\x06 \x01(\x04R\rrewardedCoins\x12!\n\x0c\x62urned_coins\x18\x07 \x01(\x04R\x0b\x62urnedCoins\x12\x31\n\x14validated_inferences\x18\x08 \x01(\x04R\x13validatedInferences\x12\x35\n\x16invalidated_inferences\x18\t \x01(\x04R\x15invalidatedInferences\x12\x18\n\x07\x63laimed\x18\n \x01(\x08R\x07\x63laimedB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.epoch_performance_summary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_EPOCHPERFORMANCESUMMARY']._serialized_start=77
  _globals['_EPOCHPERFORMANCESUMMARY']._serialized_end=497
# @@protoc_insertion_point(module_scope)
