# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/excluded_participant.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.inference/inference/excluded_participant.proto\x12\x13inference.inference\x1a\x14gogoproto/gogo.proto\"\x9e\x01\n\x13\x45xcludedParticipant\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x1f\n\x0b\x65poch_index\x18\x02 \x01(\x04R\nepochIndex\x12\x16\n\x06reason\x18\x03 \x01(\tR\x06reason\x12\x34\n\x16\x65xclusion_block_height\x18\x04 \x01(\x04R\x14\x65xclusionBlockHeightB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.excluded_participant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_EXCLUDEDPARTICIPANT']._serialized_start=94
  _globals['_EXCLUDEDPARTICIPANT']._serialized_end=252
# @@protoc_insertion_point(module_scope)
