# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/genesis.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.inference import params_pb2 as inference_dot_inference_dot_params__pb2
from inference.inference import inference_pb2 as inference_dot_inference_dot_inference__pb2
from inference.inference import participant_pb2 as inference_dot_inference_dot_participant__pb2
from inference.inference import epoch_group_data_pb2 as inference_dot_inference_dot_epoch__group__data__pb2
from inference.inference import settle_amount_pb2 as inference_dot_inference_dot_settle__amount__pb2
from inference.inference import epoch_group_validations_pb2 as inference_dot_inference_dot_epoch__group__validations__pb2
from inference.inference import tokenomics_data_pb2 as inference_dot_inference_dot_tokenomics__data__pb2
from inference.inference import model_pb2 as inference_dot_inference_dot_model__pb2
from inference.inference import inference_timeout_pb2 as inference_dot_inference_dot_inference__timeout__pb2
from inference.inference import inference_validation_details_pb2 as inference_dot_inference_dot_inference__validation__details__pb2
from inference.inference import epoch_performance_summary_pb2 as inference_dot_inference_dot_epoch__performance__summary__pb2
from inference.inference import partial_upgrade_pb2 as inference_dot_inference_dot_partial__upgrade__pb2
from inference.inference import bridge_pb2 as inference_dot_inference_dot_bridge__pb2
from inference.inference import mlnode_version_pb2 as inference_dot_inference_dot_mlnode__version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!inference/inference/genesis.proto\x12\x13inference.inference\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a inference/inference/params.proto\x1a#inference/inference/inference.proto\x1a%inference/inference/participant.proto\x1a*inference/inference/epoch_group_data.proto\x1a\'inference/inference/settle_amount.proto\x1a\x31inference/inference/epoch_group_validations.proto\x1a)inference/inference/tokenomics_data.proto\x1a\x1finference/inference/model.proto\x1a+inference/inference/inference_timeout.proto\x1a\x36inference/inference/inference_validation_details.proto\x1a\x33inference/inference/epoch_performance_summary.proto\x1a)inference/inference/partial_upgrade.proto\x1a inference/inference/bridge.proto\x1a(inference/inference/mlnode_version.proto\"U\n\x0e\x43osmWasmParams\x12\x1b\n\tcw20_code\x18\x01 \x01(\x0cR\x08\x63w20Code\x12 \n\x0c\x63w20_code_id\x18\x02 \x01(\x04R\ncw20CodeId:\x04\xe8\xa0\x1f\x01\"\x9d\x04\n\x0cGenesisState\x12>\n\x06params\x18\x01 \x01(\x0b\x32\x1b.inference.inference.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12\x61\n\x13genesis_only_params\x18\x02 \x01(\x0b\x32&.inference.inference.GenesisOnlyParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x11genesisOnlyParams\x12?\n\nmodel_list\x18\x03 \x03(\x0b\x32\x1a.inference.inference.ModelB\x04\xc8\xde\x1f\x00R\tmodelList\x12Q\n\x10\x63osm_wasm_params\x18\x04 \x01(\x0b\x32#.inference.inference.CosmWasmParamsB\x02\x18\x01R\x0e\x63osmWasmParams\x12V\n\x10participant_list\x18\x05 \x03(\x0b\x32 .inference.inference.ParticipantB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x0fparticipantList\x12I\n\x0emlnode_version\x18\x06 \x01(\x0b\x32\".inference.inference.MLNodeVersionR\rmlnodeVersion\x12\x33\n\x06\x62ridge\x18\x07 \x01(\x0b\x32\x1b.inference.inference.BridgeR\x06\x62ridgeB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_COSMWASMPARAMS']._options = None
  _globals['_COSMWASMPARAMS']._serialized_options = b'\350\240\037\001'
  _globals['_GENESISSTATE'].fields_by_name['params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['genesis_only_params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['genesis_only_params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['model_list']._options = None
  _globals['_GENESISSTATE'].fields_by_name['model_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['cosm_wasm_params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['cosm_wasm_params']._serialized_options = b'\030\001'
  _globals['_GENESISSTATE'].fields_by_name['participant_list']._options = None
  _globals['_GENESISSTATE'].fields_by_name['participant_list']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_COSMWASMPARAMS']._serialized_start=694
  _globals['_COSMWASMPARAMS']._serialized_end=779
  _globals['_GENESISSTATE']._serialized_start=782
  _globals['_GENESISSTATE']._serialized_end=1323
# @@protoc_insertion_point(module_scope)
