# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/grace_epoch_params.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.inference import params_pb2 as inference_dot_inference_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,inference/inference/grace_epoch_params.proto\x12\x13inference.inference\x1a\x14gogoproto/gogo.proto\x1a inference/inference/params.proto\"\xb1\x01\n\x10GraceEpochParams\x12\x1f\n\x0b\x65poch_index\x18\x01 \x01(\x04R\nepochIndex\x12@\n\rbinom_test_p0\x18\x02 \x01(\x0b\x32\x1c.inference.inference.DecimalR\x0b\x62inomTestP0\x12:\n\x19upgrade_protection_window\x18\x03 \x01(\x03R\x17upgradeProtectionWindowB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.grace_epoch_params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_GRACEEPOCHPARAMS']._serialized_start=126
  _globals['_GRACEEPOCHPARAMS']._serialized_end=303
# @@protoc_insertion_point(module_scope)
