# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/hardware_node.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'inference/inference/hardware_node.proto\x12\x13inference.inference\"{\n\rHardwareNodes\x12 \n\x0bparticipant\x18\x01 \x01(\tR\x0bparticipant\x12H\n\x0ehardware_nodes\x18\x02 \x03(\x0b\x32!.inference.inference.HardwareNodeR\rhardwareNodes\"\xff\x01\n\x0cHardwareNode\x12\x19\n\x08local_id\x18\x01 \x01(\tR\x07localId\x12?\n\x06status\x18\x02 \x01(\x0e\x32\'.inference.inference.HardwareNodeStatusR\x06status\x12\x16\n\x06models\x18\x03 \x03(\tR\x06models\x12\x39\n\x08hardware\x18\x04 \x03(\x0b\x32\x1d.inference.inference.HardwareR\x08hardware\x12\x12\n\x04host\x18\x05 \x01(\tR\x04host\x12\x12\n\x04port\x18\x06 \x01(\tR\x04port\x12\x18\n\x07version\x18\x07 \x01(\tR\x07version\"4\n\x08Hardware\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n\x05\x63ount\x18\x02 \x01(\rR\x05\x63ount*`\n\x12HardwareNodeStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tINFERENCE\x10\x01\x12\x07\n\x03POC\x10\x02\x12\x0c\n\x08TRAINING\x10\x03\x12\x0b\n\x07STOPPED\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\x42\x37Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.hardware_node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_HARDWARENODESTATUS']._serialized_start=501
  _globals['_HARDWARENODESTATUS']._serialized_end=597
  _globals['_HARDWARENODES']._serialized_start=64
  _globals['_HARDWARENODES']._serialized_end=187
  _globals['_HARDWARENODE']._serialized_start=190
  _globals['_HARDWARENODE']._serialized_end=445
  _globals['_HARDWARE']._serialized_start=447
  _globals['_HARDWARE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
