# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/inference_timeout.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+inference/inference/inference_timeout.proto\x12\x13inference.inference\"b\n\x10InferenceTimeout\x12+\n\x11\x65xpiration_height\x18\x01 \x01(\x04R\x10\x65xpirationHeight\x12!\n\x0cinference_id\x18\x02 \x01(\tR\x0binferenceIdB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.inference_timeout_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_INFERENCETIMEOUT']._serialized_start=68
  _globals['_INFERENCETIMEOUT']._serialized_end=166
# @@protoc_insertion_point(module_scope)
