# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/inference_validation_details.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6inference/inference/inference_validation_details.proto\x12\x13inference.inference\"\xe6\x02\n\x1aInferenceValidationDetails\x12\x19\n\x08\x65poch_id\x18\x01 \x01(\x04R\x07\x65pochId\x12!\n\x0cinference_id\x18\x02 \x01(\tR\x0binferenceId\x12\x1f\n\x0b\x65xecutor_id\x18\x03 \x01(\tR\nexecutorId\x12/\n\x13\x65xecutor_reputation\x18\x04 \x01(\x05R\x12\x65xecutorReputation\x12#\n\rtraffic_basis\x18\x05 \x01(\x04R\x0ctrafficBasis\x12%\n\x0e\x65xecutor_power\x18\x06 \x01(\x04R\rexecutorPower\x12\x14\n\x05model\x18\x07 \x01(\tR\x05model\x12\x1f\n\x0btotal_power\x18\x08 \x01(\x04R\ntotalPower\x12\x35\n\x17\x63reated_at_block_height\x18\t \x01(\x03R\x14\x63reatedAtBlockHeightB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.inference_validation_details_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_INFERENCEVALIDATIONDETAILS']._serialized_start=80
  _globals['_INFERENCEVALIDATIONDETAILS']._serialized_end=438
# @@protoc_insertion_point(module_scope)
