# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/model.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from inference.inference import params_pb2 as inference_dot_inference_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1finference/inference/model.proto\x12\x13inference.inference\x1a inference/inference/params.proto\"\x94\x04\n\x05Model\x12\x1f\n\x0bproposed_by\x18\x01 \x01(\tR\nproposedBy\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id\x12:\n\x1aunits_of_compute_per_token\x18\x03 \x01(\x04R\x16unitsOfComputePerToken\x12%\n\x0e\x63ontext_window\x18\x04 \x01(\x04R\rcontextWindow\x12\"\n\x0cquantization\x18\x05 \x01(\tR\x0cquantization\x12\x31\n\x15\x63oins_per_input_token\x18\x06 \x01(\x04R\x12\x63oinsPerInputToken\x12\x33\n\x16\x63oins_per_output_token\x18\x07 \x01(\x04R\x13\x63oinsPerOutputToken\x12\x17\n\x07hf_repo\x18\x08 \x01(\tR\x06hfRepo\x12\x1b\n\thf_commit\x18\t \x01(\tR\x08hfCommit\x12\x1d\n\nmodel_args\x18\n \x03(\tR\tmodelArgs\x12\x13\n\x05v_ram\x18\x0b \x01(\x04R\x04vRam\x12\x30\n\x14throughput_per_nonce\x18\x0c \x01(\x04R\x12throughputPerNonce\x12O\n\x14validation_threshold\x18\r \x01(\x0b\x32\x1c.inference.inference.DecimalR\x13validationThresholdB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_MODEL']._serialized_start=91
  _globals['_MODEL']._serialized_end=623
# @@protoc_insertion_point(module_scope)
