# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/partial_upgrade.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)inference/inference/partial_upgrade.proto\x12\x13inference.inference\"\x8b\x01\n\x0ePartialUpgrade\x12\x16\n\x06height\x18\x01 \x01(\x04R\x06height\x12!\n\x0cnode_version\x18\x02 \x01(\tR\x0bnodeVersion\x12*\n\x11\x61pi_binaries_json\x18\x03 \x01(\tR\x0f\x61piBinariesJson\x12\x12\n\x04name\x18\x04 \x01(\tR\x04nameB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.partial_upgrade_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_PARTIALUPGRADE']._serialized_start=67
  _globals['_PARTIALUPGRADE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
