# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/poc_validation_snapshot.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1inference/inference/poc_validation_snapshot.proto\x12\x13inference.inference\"\x94\x03\n\x15PoCValidationSnapshot\x12\x33\n\x16poc_stage_start_height\x18\x01 \x01(\x03R\x13pocStageStartHeight\x12\'\n\x0fsnapshot_height\x18\x02 \x01(\x03R\x0esnapshotHeight\x12\x19\n\x08\x61pp_hash\x18\x03 \x01(\tR\x07\x61ppHash\x12<\n\x1ageneration_start_timestamp\x18\x05 \x01(\x03R\x18generationStartTimestamp\x12\x34\n\x16\x65xchange_end_timestamp\x18\x06 \x01(\x03R\x14\x65xchangeEndTimestamp\x12V\n\x13model_voting_powers\x18\x07 \x03(\x0b\x32&.inference.inference.ModelVotingPowersR\x11modelVotingPowers\x12\x30\n\x14total_network_weight\x18\x08 \x01(\x03R\x12totalNetworkWeightJ\x04\x08\x04\x10\x05\"z\n\x11ModelVotingPowers\x12\x19\n\x08model_id\x18\x01 \x01(\tR\x07modelId\x12J\n\rvoting_powers\x18\x02 \x03(\x0b\x32%.inference.inference.VotingPowerEntryR\x0cvotingPowers\"O\n\x10VotingPowerEntry\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12!\n\x0cvoting_power\x18\x02 \x01(\x03R\x0bvotingPowerB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.poc_validation_snapshot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_POCVALIDATIONSNAPSHOT']._serialized_start=75
  _globals['_POCVALIDATIONSNAPSHOT']._serialized_end=479
  _globals['_MODELVOTINGPOWERS']._serialized_start=481
  _globals['_MODELVOTINGPOWERS']._serialized_end=603
  _globals['_VOTINGPOWERENTRY']._serialized_start=605
  _globals['_VOTINGPOWERENTRY']._serialized_end=684
# @@protoc_insertion_point(module_scope)
