# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/pocbatch.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"inference/inference/pocbatch.proto\x12\x13inference.inference\"\x94\x02\n\x08PoCBatch\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12>\n\x1cpoc_stage_start_block_height\x18\x02 \x01(\x03R\x18pocStageStartBlockHeight\x12\x37\n\x18received_at_block_height\x18\x03 \x01(\x03R\x15receivedAtBlockHeight\x12\x16\n\x06nonces\x18\x04 \x03(\x03R\x06nonces\x12\x12\n\x04\x64ist\x18\x05 \x03(\x01R\x04\x64ist\x12\x19\n\x08\x62\x61tch_id\x18\x06 \x01(\tR\x07\x62\x61tchId\x12\x17\n\x07node_id\x18\x07 \x01(\tR\x06nodeId\"\x87\x04\n\rPoCValidation\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12\x42\n\x1dvalidator_participant_address\x18\x02 \x01(\tR\x1bvalidatorParticipantAddress\x12>\n\x1cpoc_stage_start_block_height\x18\x03 \x01(\x03R\x18pocStageStartBlockHeight\x12\x39\n\x19validated_at_block_height\x18\x04 \x01(\x03R\x16validatedAtBlockHeight\x12\x16\n\x06nonces\x18\x05 \x03(\x03R\x06nonces\x12\x12\n\x04\x64ist\x18\x06 \x03(\x01R\x04\x64ist\x12#\n\rreceived_dist\x18\x07 \x03(\x01R\x0creceivedDist\x12\x19\n\x08r_target\x18\x08 \x01(\x01R\x07rTarget\x12\'\n\x0f\x66raud_threshold\x18\t \x01(\x01R\x0e\x66raudThreshold\x12\x1b\n\tn_invalid\x18\n \x01(\x03R\x08nInvalid\x12-\n\x12probability_honest\x18\x0b \x01(\x01R\x11probabilityHonest\x12%\n\x0e\x66raud_detected\x18\x0c \x01(\x08R\rfraudDetectedB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.pocbatch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_POCBATCH']._serialized_start=60
  _globals['_POCBATCH']._serialized_end=336
  _globals['_POCVALIDATION']._serialized_start=339
  _globals['_POCVALIDATION']._serialized_end=858
# @@protoc_insertion_point(module_scope)
