# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/preserved_nodes_snapshot.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2inference/inference/preserved_nodes_snapshot.proto\x12\x13inference.inference\"\xaa\x01\n\x16PreservedNodesSnapshot\x12\x32\n\x15\x65pisode_anchor_height\x18\x01 \x01(\x03R\x13\x65pisodeAnchorHeight\x12\\\n\x15model_preserved_nodes\x18\x02 \x03(\x0b\x32(.inference.inference.ModelPreservedNodesR\x13modelPreservedNodes\"\x84\x01\n\x13ModelPreservedNodes\x12\x19\n\x08model_id\x18\x01 \x01(\tR\x07modelId\x12R\n\x0cparticipants\x18\x02 \x03(\x0b\x32..inference.inference.ParticipantPreservedNodesR\x0cparticipants\"]\n\x19ParticipantPreservedNodes\x12%\n\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x19\n\x08node_ids\x18\x02 \x03(\tR\x07nodeIdsB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.preserved_nodes_snapshot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_PRESERVEDNODESSNAPSHOT']._serialized_start=76
  _globals['_PRESERVEDNODESSNAPSHOT']._serialized_end=246
  _globals['_MODELPRESERVEDNODES']._serialized_start=249
  _globals['_MODELPRESERVEDNODES']._serialized_end=381
  _globals['_PARTICIPANTPRESERVEDNODES']._serialized_start=383
  _globals['_PARTICIPANTPRESERVEDNODES']._serialized_end=476
# @@protoc_insertion_point(module_scope)
