# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/random_seed.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%inference/inference/random_seed.proto\x12\x13inference.inference\"m\n\nRandomSeed\x12 \n\x0bparticipant\x18\x01 \x01(\tR\x0bparticipant\x12\x1f\n\x0b\x65poch_index\x18\x02 \x01(\x04R\nepochIndex\x12\x1c\n\tsignature\x18\x03 \x01(\tR\tsignatureB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.random_seed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_RANDOMSEED']._serialized_start=62
  _globals['_RANDOMSEED']._serialized_end=171
# @@protoc_insertion_point(module_scope)
