# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/settle_amount.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'inference/inference/settle_amount.proto\x12\x13inference.inference\"\xe8\x01\n\x0cSettleAmount\x12 \n\x0bparticipant\x18\x01 \x01(\tR\x0bparticipant\x12!\n\x0creward_coins\x18\x02 \x01(\x04R\x0brewardCoins\x12\x1d\n\nwork_coins\x18\x03 \x01(\x04R\tworkCoins\x12\x1f\n\x0b\x65poch_index\x18\x04 \x01(\x04R\nepochIndex\x12%\n\x0eseed_signature\x18\x05 \x01(\tR\rseedSignature\x12,\n\x12last_claim_attempt\x18\x06 \x01(\x03R\x10lastClaimAttemptB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.settle_amount_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_SETTLEAMOUNT']._serialized_start=65
  _globals['_SETTLEAMOUNT']._serialized_end=297
# @@protoc_insertion_point(module_scope)
