# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/sprt.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.inference import params_pb2 as inference_dot_inference_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1einference/inference/sprt.proto\x12\x13inference.inference\x1a\x14gogoproto/gogo.proto\x1a inference/inference/params.proto\"\xd5\x02\n\x15SPRTPrecomputedValues\x12P\n\x15invalidation_log_fail\x18\x01 \x01(\x0b\x32\x1c.inference.inference.DecimalR\x13invalidationLogFail\x12P\n\x15invalidation_log_pass\x18\x02 \x01(\x0b\x32\x1c.inference.inference.DecimalR\x13invalidationLogPass\x12H\n\x11inactive_log_fail\x18\x03 \x01(\x0b\x32\x1c.inference.inference.DecimalR\x0finactiveLogFail\x12H\n\x11inactive_log_pass\x18\x04 \x01(\x0b\x32\x1c.inference.inference.DecimalR\x0finactiveLogPass:\x04\xe8\xa0\x1f\x01\x42\x37Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.sprt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_SPRTPRECOMPUTEDVALUES']._options = None
  _globals['_SPRTPRECOMPUTEDVALUES']._serialized_options = b'\350\240\037\001'
  _globals['_SPRTPRECOMPUTEDVALUES']._serialized_start=112
  _globals['_SPRTPRECOMPUTEDVALUES']._serialized_end=453
# @@protoc_insertion_point(module_scope)
