# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/stats_developer.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from inference.inference import inference_pb2 as inference_dot_inference_dot_inference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)inference/inference/stats_developer.proto\x12\x13inference.inference\x1a#inference/inference/inference.proto\"W\n\x15\x44\x65veloperStatsByEpoch\x12\x19\n\x08\x65poch_id\x18\x01 \x01(\x04R\x07\x65pochId\x12#\n\rinference_ids\x18\x02 \x03(\tR\x0cinferenceIds\"\xff\x01\n\x0eInferenceStats\x12!\n\x0cinference_id\x18\x01 \x01(\tR\x0binferenceId\x12\x19\n\x08\x65poch_id\x18\x02 \x01(\x04R\x07\x65pochId\x12<\n\x06status\x18\x03 \x01(\x0e\x32$.inference.inference.InferenceStatusR\x06status\x12*\n\x11total_token_count\x18\x04 \x01(\x04R\x0ftotalTokenCount\x12\x14\n\x05model\x18\x05 \x01(\tR\x05model\x12/\n\x14\x61\x63tual_cost_in_coins\x18\x06 \x01(\x03R\x11\x61\x63tualCostInCoins\"\x92\x01\n\x14\x44\x65veloperStatsByTime\x12\x19\n\x08\x65poch_id\x18\x01 \x01(\x04R\x07\x65pochId\x12\x1c\n\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x41\n\tinference\x18\x03 \x01(\x0b\x32#.inference.inference.InferenceStatsR\tinferenceB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.stats_developer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_DEVELOPERSTATSBYEPOCH']._serialized_start=103
  _globals['_DEVELOPERSTATSBYEPOCH']._serialized_end=190
  _globals['_INFERENCESTATS']._serialized_start=193
  _globals['_INFERENCESTATS']._serialized_end=448
  _globals['_DEVELOPERSTATSBYTIME']._serialized_start=451
  _globals['_DEVELOPERSTATSBYTIME']._serialized_end=597
# @@protoc_insertion_point(module_scope)
