# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/top_miner.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#inference/inference/top_miner.proto\x12\x13inference.inference\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\xfb\x03\n\x08TopMiner\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x34\n\x16last_qualified_started\x18\x02 \x01(\x03R\x14lastQualifiedStarted\x12,\n\x12rewards_paid_count\x18\x03 \x01(\x05R\x10rewardsPaidCount\x12\'\n\x0crewards_paid\x18\x04 \x03(\x03\x42\x04\xc8\xde\x1f\x00R\x0brewardsPaid\x12+\n\x11qualified_periods\x18\x05 \x01(\x05R\x10qualifiedPeriods\x12%\n\x0emissed_periods\x18\x06 \x01(\x05R\rmissedPeriods\x12%\n\x0equalified_time\x18\x07 \x01(\x03R\rqualifiedTime\x12\x1f\n\x0bmissed_time\x18\x08 \x01(\x03R\nmissedTime\x12*\n\x11last_updated_time\x18\t \x01(\x03R\x0flastUpdatedTime\x12\x36\n\x17\x66irst_qualified_started\x18\n \x01(\x03R\x15\x66irstQualifiedStarted\x12#\n\rinitial_power\x18\x0b \x01(\x03R\x0cinitialPower\x12#\n\rinitial_order\x18\x0c \x01(\x05R\x0cinitialOrderB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.top_miner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_TOPMINER'].fields_by_name['rewards_paid']._options = None
  _globals['_TOPMINER'].fields_by_name['rewards_paid']._serialized_options = b'\310\336\037\000'
  _globals['_TOPMINER']._serialized_start=115
  _globals['_TOPMINER']._serialized_end=622
# @@protoc_insertion_point(module_scope)
