# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/unit_of_compute.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)inference/inference/unit_of_compute.proto\x12\x13inference.inference\"\xb9\x01\n\x1aUnitOfComputePriceProposal\x12 \n\x0bparticipant\x18\x01 \x01(\tR\x0bparticipant\x12\x14\n\x05price\x18\x02 \x01(\x04R\x05price\x12\x37\n\x18proposed_at_block_height\x18\x03 \x01(\x04R\x15proposedAtBlockHeight\x12*\n\x11proposed_at_epoch\x18\x04 \x01(\x04R\x0fproposedAtEpochB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.unit_of_compute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_UNITOFCOMPUTEPRICEPROPOSAL']._serialized_start=67
  _globals['_UNITOFCOMPUTEPRICEPROPOSAL']._serialized_end=252
# @@protoc_insertion_point(module_scope)
