# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/restrictions/params.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#inference/restrictions/params.proto\x12\x16inference.restrictions\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"\x90\x02\n\x1a\x45mergencyTransferExemption\x12!\n\x0c\x65xemption_id\x18\x01 \x01(\tR\x0b\x65xemptionId\x12!\n\x0c\x66rom_address\x18\x02 \x01(\tR\x0b\x66romAddress\x12\x1d\n\nto_address\x18\x03 \x01(\tR\ttoAddress\x12\x1d\n\nmax_amount\x18\x04 \x01(\tR\tmaxAmount\x12\x1f\n\x0busage_limit\x18\x05 \x01(\x04R\nusageLimit\x12!\n\x0c\x65xpiry_block\x18\x06 \x01(\x04R\x0b\x65xpiryBlock\x12$\n\rjustification\x18\x07 \x01(\tR\rjustification:\x04\xe8\xa0\x1f\x01\"\x83\x01\n\x0e\x45xemptionUsage\x12!\n\x0c\x65xemption_id\x18\x01 \x01(\tR\x0b\x65xemptionId\x12\'\n\x0f\x61\x63\x63ount_address\x18\x02 \x01(\tR\x0e\x61\x63\x63ountAddress\x12\x1f\n\x0busage_count\x18\x03 \x01(\x04R\nusageCount:\x04\xe8\xa0\x1f\x01\"\xcc\x02\n\x06Params\x12\x32\n\x15restriction_end_block\x18\x01 \x01(\x04R\x13restrictionEndBlock\x12|\n\x1d\x65mergency_transfer_exemptions\x18\x02 \x03(\x0b\x32\x32.inference.restrictions.EmergencyTransferExemptionB\x04\xc8\xde\x1f\x00R\x1b\x65mergencyTransferExemptions\x12\x66\n\x18\x65xemption_usage_tracking\x18\x03 \x03(\x0b\x32&.inference.restrictions.ExemptionUsageB\x04\xc8\xde\x1f\x00R\x16\x65xemptionUsageTracking:(\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x1finference/x/restrictions/ParamsB:Z8github.com/productscience/inference/x/restrictions/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.restrictions.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/productscience/inference/x/restrictions/types'
  _globals['_EMERGENCYTRANSFEREXEMPTION']._options = None
  _globals['_EMERGENCYTRANSFEREXEMPTION']._serialized_options = b'\350\240\037\001'
  _globals['_EXEMPTIONUSAGE']._options = None
  _globals['_EXEMPTIONUSAGE']._serialized_options = b'\350\240\037\001'
  _globals['_PARAMS'].fields_by_name['emergency_transfer_exemptions']._options = None
  _globals['_PARAMS'].fields_by_name['emergency_transfer_exemptions']._serialized_options = b'\310\336\037\000'
  _globals['_PARAMS'].fields_by_name['exemption_usage_tracking']._options = None
  _globals['_PARAMS'].fields_by_name['exemption_usage_tracking']._serialized_options = b'\310\336\037\000'
  _globals['_PARAMS']._options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\037inference/x/restrictions/Params'
  _globals['_EMERGENCYTRANSFEREXEMPTION']._serialized_start=105
  _globals['_EMERGENCYTRANSFEREXEMPTION']._serialized_end=377
  _globals['_EXEMPTIONUSAGE']._serialized_start=380
  _globals['_EXEMPTIONUSAGE']._serialized_end=511
  _globals['_PARAMS']._serialized_start=514
  _globals['_PARAMS']._serialized_end=846
# @@protoc_insertion_point(module_scope)
