# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/restrictions/tx.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.restrictions import params_pb2 as inference_dot_restrictions_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1finference/restrictions/tx.proto\x12\x16inference.restrictions\x1a\x11\x61mino/amino.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a#inference/restrictions/params.proto\"\xc9\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12\x41\n\x06params\x18\x02 \x01(\x0b\x32\x1e.inference.restrictions.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:;\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*(inference/x/restrictions/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse\"\xb0\x02\n\x1bMsgExecuteEmergencyTransfer\x12!\n\x0c\x65xemption_id\x18\x01 \x01(\tR\x0b\x65xemptionId\x12;\n\x0c\x66rom_address\x18\x02 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x0b\x66romAddress\x12\x37\n\nto_address\x18\x03 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\ttoAddress\x12\x16\n\x06\x61mount\x18\x04 \x01(\tR\x06\x61mount\x12\x14\n\x05\x64\x65nom\x18\x05 \x01(\tR\x05\x64\x65nom:J\x82\xe7\xb0*\x0c\x66rom_address\x8a\xe7\xb0*4inference/x/restrictions/MsgExecuteEmergencyTransfer\"L\n#MsgExecuteEmergencyTransferResponse\x12%\n\x0eremaining_uses\x18\x01 \x01(\x04R\rremainingUses2\x85\x02\n\x03Msg\x12h\n\x0cUpdateParams\x12\'.inference.restrictions.MsgUpdateParams\x1a/.inference.restrictions.MsgUpdateParamsResponse\x12\x8c\x01\n\x18\x45xecuteEmergencyTransfer\x12\x33.inference.restrictions.MsgExecuteEmergencyTransfer\x1a;.inference.restrictions.MsgExecuteEmergencyTransferResponse\x1a\x05\x80\xe7\xb0*\x01\x42:Z8github.com/productscience/inference/x/restrictions/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.restrictions.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/productscience/inference/x/restrictions/types'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260*(inference/x/restrictions/MsgUpdateParams'
  _globals['_MSGEXECUTEEMERGENCYTRANSFER'].fields_by_name['from_address']._options = None
  _globals['_MSGEXECUTEEMERGENCYTRANSFER'].fields_by_name['from_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGEXECUTEEMERGENCYTRANSFER'].fields_by_name['to_address']._options = None
  _globals['_MSGEXECUTEEMERGENCYTRANSFER'].fields_by_name['to_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGEXECUTEEMERGENCYTRANSFER']._options = None
  _globals['_MSGEXECUTEEMERGENCYTRANSFER']._serialized_options = b'\202\347\260*\014from_address\212\347\260*4inference/x/restrictions/MsgExecuteEmergencyTransfer'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=190
  _globals['_MSGUPDATEPARAMS']._serialized_end=391
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=393
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=418
  _globals['_MSGEXECUTEEMERGENCYTRANSFER']._serialized_start=421
  _globals['_MSGEXECUTEEMERGENCYTRANSFER']._serialized_end=725
  _globals['_MSGEXECUTEEMERGENCYTRANSFERRESPONSE']._serialized_start=727
  _globals['_MSGEXECUTEEMERGENCYTRANSFERRESPONSE']._serialized_end=803
  _globals['_MSG']._serialized_start=806
  _globals['_MSG']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
