# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/genesistransfer/genesis.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.genesistransfer import params_pb2 as inference_dot_genesistransfer_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'inference/genesistransfer/genesis.proto\x12\x19inference.genesistransfer\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a&inference/genesistransfer/params.proto\"\x8b\x02\n\x0eTransferRecord\x12\'\n\x0fgenesis_address\x18\x01 \x01(\tR\x0egenesisAddress\x12+\n\x11recipient_address\x18\x02 \x01(\tR\x10recipientAddress\x12\'\n\x0ftransfer_height\x18\x03 \x01(\x04R\x0etransferHeight\x12\x1c\n\tcompleted\x18\x04 \x01(\x08R\tcompleted\x12-\n\x12transferred_denoms\x18\x05 \x03(\tR\x11transferredDenoms\x12\'\n\x0ftransfer_amount\x18\x06 \x01(\tR\x0etransferAmount:\x04\xe8\xa0\x1f\x01\"\xb5\x01\n\x0cGenesisState\x12\x44\n\x06params\x18\x01 \x01(\x0b\x32!.inference.genesistransfer.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12_\n\x10transfer_records\x18\x02 \x03(\x0b\x32).inference.genesistransfer.TransferRecordB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x0ftransferRecordsB=Z;github.com/productscience/inference/x/genesistransfer/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.genesistransfer.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/productscience/inference/x/genesistransfer/types'
  _globals['_TRANSFERRECORD']._options = None
  _globals['_TRANSFERRECORD']._serialized_options = b'\350\240\037\001'
  _globals['_GENESISSTATE'].fields_by_name['params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['transfer_records']._options = None
  _globals['_GENESISSTATE'].fields_by_name['transfer_records']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_TRANSFERRECORD']._serialized_start=152
  _globals['_TRANSFERRECORD']._serialized_end=419
  _globals['_GENESISSTATE']._serialized_start=422
  _globals['_GENESISSTATE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
