# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/genesistransfer/params.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&inference/genesistransfer/params.proto\x12\x19inference.genesistransfer\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"\x95\x01\n\x06Params\x12\x34\n\x10\x61llowed_accounts\x18\x01 \x03(\tB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x0f\x61llowedAccounts\x12(\n\x10restrict_to_list\x18\x02 \x01(\x08R\x0erestrictToList:+\xe8\xa0\x1f\x01\x8a\xe7\xb0*\"inference/x/genesistransfer/ParamsB=Z;github.com/productscience/inference/x/genesistransfer/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.genesistransfer.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/productscience/inference/x/genesistransfer/types'
  _globals['_PARAMS'].fields_by_name['allowed_accounts']._options = None
  _globals['_PARAMS'].fields_by_name['allowed_accounts']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_PARAMS']._options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\"inference/x/genesistransfer/Params'
  _globals['_PARAMS']._serialized_start=111
  _globals['_PARAMS']._serialized_end=260
# @@protoc_insertion_point(module_scope)
