# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/genesistransfer/tx.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.genesistransfer import params_pb2 as inference_dot_genesistransfer_dot_params__pb2
from inference.genesistransfer import genesis_pb2 as inference_dot_genesistransfer_dot_genesis__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"inference/genesistransfer/tx.proto\x12\x19inference.genesistransfer\x1a\x11\x61mino/amino.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a&inference/genesistransfer/params.proto\x1a\'inference/genesistransfer/genesis.proto\"\xcf\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12\x44\n\x06params\x18\x02 \x01(\x0b\x32!.inference.genesistransfer.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:>\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*+inference/x/genesistransfer/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse\"\xeb\x01\n\x14MsgTransferOwnership\x12\x41\n\x0fgenesis_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x0egenesisAddress\x12\x45\n\x11recipient_address\x18\x02 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x10recipientAddress:I\x82\xe7\xb0*\x0fgenesis_address\x8a\xe7\xb0*0inference/x/genesistransfer/MsgTransferOwnership\"}\n\x1cMsgTransferOwnershipResponse\x12]\n\x0ftransfer_record\x18\x01 \x01(\x0b\x32).inference.genesistransfer.TransferRecordB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x0etransferRecord2\xfb\x01\n\x03Msg\x12n\n\x0cUpdateParams\x12*.inference.genesistransfer.MsgUpdateParams\x1a\x32.inference.genesistransfer.MsgUpdateParamsResponse\x12}\n\x11TransferOwnership\x12/.inference.genesistransfer.MsgTransferOwnership\x1a\x37.inference.genesistransfer.MsgTransferOwnershipResponse\x1a\x05\x80\xe7\xb0*\x01\x42=Z;github.com/productscience/inference/x/genesistransfer/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.genesistransfer.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/productscience/inference/x/genesistransfer/types'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260*+inference/x/genesistransfer/MsgUpdateParams'
  _globals['_MSGTRANSFEROWNERSHIP'].fields_by_name['genesis_address']._options = None
  _globals['_MSGTRANSFEROWNERSHIP'].fields_by_name['genesis_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGTRANSFEROWNERSHIP'].fields_by_name['recipient_address']._options = None
  _globals['_MSGTRANSFEROWNERSHIP'].fields_by_name['recipient_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGTRANSFEROWNERSHIP']._options = None
  _globals['_MSGTRANSFEROWNERSHIP']._serialized_options = b'\202\347\260*\017genesis_address\212\347\260*0inference/x/genesistransfer/MsgTransferOwnership'
  _globals['_MSGTRANSFEROWNERSHIPRESPONSE'].fields_by_name['transfer_record']._options = None
  _globals['_MSGTRANSFEROWNERSHIPRESPONSE'].fields_by_name['transfer_record']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=240
  _globals['_MSGUPDATEPARAMS']._serialized_end=447
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=449
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=474
  _globals['_MSGTRANSFEROWNERSHIP']._serialized_start=477
  _globals['_MSGTRANSFEROWNERSHIP']._serialized_end=712
  _globals['_MSGTRANSFEROWNERSHIPRESPONSE']._serialized_start=714
  _globals['_MSGTRANSFEROWNERSHIPRESPONSE']._serialized_end=839
  _globals['_MSG']._serialized_start=842
  _globals['_MSG']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
