# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/streamvesting/genesis.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.streamvesting import params_pb2 as inference_dot_streamvesting_dot_params__pb2
from inference.streamvesting import vesting_schedule_pb2 as inference_dot_streamvesting_dot_vesting__schedule__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%inference/streamvesting/genesis.proto\x12\x17inference.streamvesting\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a$inference/streamvesting/params.proto\x1a.inference/streamvesting/vesting_schedule.proto\"\xbb\x01\n\x0cGenesisState\x12\x42\n\x06params\x18\x01 \x01(\x0b\x32\x1f.inference.streamvesting.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12g\n\x15vesting_schedule_list\x18\x02 \x03(\x0b\x32(.inference.streamvesting.VestingScheduleB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x13vestingScheduleListB;Z9github.com/productscience/inference/x/streamvesting/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.streamvesting.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/productscience/inference/x/streamvesting/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['vesting_schedule_list']._options = None
  _globals['_GENESISSTATE'].fields_by_name['vesting_schedule_list']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE']._serialized_start=194
  _globals['_GENESISSTATE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
