# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/streamvesting/query.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from inference.streamvesting import params_pb2 as inference_dot_streamvesting_dot_params__pb2
from inference.streamvesting import vesting_schedule_pb2 as inference_dot_streamvesting_dot_vesting__schedule__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#inference/streamvesting/query.proto\x12\x17inference.streamvesting\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a$inference/streamvesting/params.proto\x1a.inference/streamvesting/vesting_schedule.proto\"\x14\n\x12QueryParamsRequest\"Y\n\x13QueryParamsResponse\x12\x42\n\x06params\x18\x01 \x01(\x0b\x32\x1f.inference.streamvesting.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"N\n\x1bQueryVestingScheduleRequest\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\"s\n\x1cQueryVestingScheduleResponse\x12S\n\x10vesting_schedule\x18\x01 \x01(\x0b\x32(.inference.streamvesting.VestingScheduleR\x0fvestingSchedule\"Q\n\x1eQueryTotalVestingAmountRequest\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\"\x96\x01\n\x1fQueryTotalVestingAmountResponse\x12s\n\x0ctotal_amount\x18\x01 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB5\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins\xa8\xe7\xb0*\x01R\x0btotalAmount2\xdd\x04\n\x05Query\x12\x9b\x01\n\x06Params\x12+.inference.streamvesting.QueryParamsRequest\x1a,.inference.streamvesting.QueryParamsResponse\"6\x82\xd3\xe4\x93\x02\x30\x12./productscience/inference/streamvesting/params\x12\xd6\x01\n\x0fVestingSchedule\x12\x34.inference.streamvesting.QueryVestingScheduleRequest\x1a\x35.inference.streamvesting.QueryVestingScheduleResponse\"V\x82\xd3\xe4\x93\x02P\x12N/productscience/inference/streamvesting/vesting_schedule/{participant_address}\x12\xdc\x01\n\x12TotalVestingAmount\x12\x37.inference.streamvesting.QueryTotalVestingAmountRequest\x1a\x38.inference.streamvesting.QueryTotalVestingAmountResponse\"S\x82\xd3\xe4\x93\x02M\x12K/productscience/inference/streamvesting/total_vesting/{participant_address}B;Z9github.com/productscience/inference/x/streamvesting/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.streamvesting.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/productscience/inference/x/streamvesting/types'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERYTOTALVESTINGAMOUNTRESPONSE'].fields_by_name['total_amount']._options = None
  _globals['_QUERYTOTALVESTINGAMOUNTRESPONSE'].fields_by_name['total_amount']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\0020\022./productscience/inference/streamvesting/params'
  _globals['_QUERY'].methods_by_name['VestingSchedule']._options = None
  _globals['_QUERY'].methods_by_name['VestingSchedule']._serialized_options = b'\202\323\344\223\002P\022N/productscience/inference/streamvesting/vesting_schedule/{participant_address}'
  _globals['_QUERY'].methods_by_name['TotalVestingAmount']._options = None
  _globals['_QUERY'].methods_by_name['TotalVestingAmount']._serialized_options = b'\202\323\344\223\002M\022K/productscience/inference/streamvesting/total_vesting/{participant_address}'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=297
  _globals['_QUERYPARAMSREQUEST']._serialized_end=317
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=319
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=408
  _globals['_QUERYVESTINGSCHEDULEREQUEST']._serialized_start=410
  _globals['_QUERYVESTINGSCHEDULEREQUEST']._serialized_end=488
  _globals['_QUERYVESTINGSCHEDULERESPONSE']._serialized_start=490
  _globals['_QUERYVESTINGSCHEDULERESPONSE']._serialized_end=605
  _globals['_QUERYTOTALVESTINGAMOUNTREQUEST']._serialized_start=607
  _globals['_QUERYTOTALVESTINGAMOUNTREQUEST']._serialized_end=688
  _globals['_QUERYTOTALVESTINGAMOUNTRESPONSE']._serialized_start=691
  _globals['_QUERYTOTALVESTINGAMOUNTRESPONSE']._serialized_end=841
  _globals['_QUERY']._serialized_start=844
  _globals['_QUERY']._serialized_end=1449
# @@protoc_insertion_point(module_scope)
