# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/streamvesting/vesting_schedule.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.inference/streamvesting/vesting_schedule.proto\x12\x17inference.streamvesting\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"z\n\nEpochCoins\x12\x66\n\x05\x63oins\x18\x01 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB5\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins\xa8\xe7\xb0*\x01R\x05\x63oins:\x04\xe8\xa0\x1f\x01\"\x9d\x01\n\x0fVestingSchedule\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12S\n\repoch_amounts\x18\x02 \x03(\x0b\x32#.inference.streamvesting.EpochCoinsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x0c\x65pochAmounts:\x04\xe8\xa0\x1f\x01\x42;Z9github.com/productscience/inference/x/streamvesting/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.streamvesting.vesting_schedule_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/productscience/inference/x/streamvesting/types'
  _globals['_EPOCHCOINS'].fields_by_name['coins']._options = None
  _globals['_EPOCHCOINS'].fields_by_name['coins']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins\250\347\260*\001'
  _globals['_EPOCHCOINS']._options = None
  _globals['_EPOCHCOINS']._serialized_options = b'\350\240\037\001'
  _globals['_VESTINGSCHEDULE'].fields_by_name['epoch_amounts']._options = None
  _globals['_VESTINGSCHEDULE'].fields_by_name['epoch_amounts']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_VESTINGSCHEDULE']._options = None
  _globals['_VESTINGSCHEDULE']._serialized_options = b'\350\240\037\001'
  _globals['_EPOCHCOINS']._serialized_start=148
  _globals['_EPOCHCOINS']._serialized_end=270
  _globals['_VESTINGSCHEDULE']._serialized_start=273
  _globals['_VESTINGSCHEDULE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
