# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bookkeeper/params.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!inference/bookkeeper/params.proto\x12\x14inference.bookkeeper\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"0\n\x06Params:&\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x1dinference/x/bookkeeper/ParamsB8Z6github.com/productscience/inference/x/bookkeeper/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bookkeeper.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/productscience/inference/x/bookkeeper/types'
  _globals['_PARAMS']._options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\035inference/x/bookkeeper/Params'
  _globals['_PARAMS']._serialized_start=100
  _globals['_PARAMS']._serialized_end=148
# @@protoc_insertion_point(module_scope)
