# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bookkeeper/query.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from inference.bookkeeper import params_pb2 as inference_dot_bookkeeper_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n inference/bookkeeper/query.proto\x12\x14inference.bookkeeper\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a!inference/bookkeeper/params.proto\"\x14\n\x12QueryParamsRequest\"V\n\x13QueryParamsResponse\x12?\n\x06params\x18\x01 \x01(\x0b\x32\x1c.inference.bookkeeper.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params2\x9c\x01\n\x05Query\x12\x92\x01\n\x06Params\x12(.inference.bookkeeper.QueryParamsRequest\x1a).inference.bookkeeper.QueryParamsResponse\"3\x82\xd3\xe4\x93\x02-\x12+/productscience/inference/bookkeeper/paramsB8Z6github.com/productscience/inference/x/bookkeeper/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bookkeeper.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/productscience/inference/x/bookkeeper/types'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002-\022+/productscience/inference/bookkeeper/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=208
  _globals['_QUERYPARAMSREQUEST']._serialized_end=228
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=230
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=316
  _globals['_QUERY']._serialized_start=319
  _globals['_QUERY']._serialized_end=475
# @@protoc_insertion_point(module_scope)
