# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/bookkeeper/tx.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.bookkeeper import params_pb2 as inference_dot_bookkeeper_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dinference/bookkeeper/tx.proto\x12\x14inference.bookkeeper\x1a\x11\x61mino/amino.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a!inference/bookkeeper/params.proto\"\xc5\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12?\n\x06params\x18\x02 \x01(\x0b\x32\x1c.inference.bookkeeper.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:9\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*&inference/x/bookkeeper/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse2r\n\x03Msg\x12\x64\n\x0cUpdateParams\x12%.inference.bookkeeper.MsgUpdateParams\x1a-.inference.bookkeeper.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x38Z6github.com/productscience/inference/x/bookkeeper/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.bookkeeper.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/productscience/inference/x/bookkeeper/types'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260*&inference/x/bookkeeper/MsgUpdateParams'
  _globals['_MSG']._options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=184
  _globals['_MSGUPDATEPARAMS']._serialized_end=381
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=383
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=408
  _globals['_MSG']._serialized_start=410
  _globals['_MSG']._serialized_end=524
# @@protoc_insertion_point(module_scope)
