# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/collateral/collateral_balance.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-inference/collateral/collateral_balance.proto\x12\x14inference.collateral\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"n\n\x11\x43ollateralBalance\x12 \n\x0bparticipant\x18\x01 \x01(\tR\x0bparticipant\x12\x37\n\x06\x61mount\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06\x61mountB8Z6github.com/productscience/inference/x/collateral/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.collateral.collateral_balance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/productscience/inference/x/collateral/types'
  _globals['_COLLATERALBALANCE'].fields_by_name['amount']._options = None
  _globals['_COLLATERALBALANCE'].fields_by_name['amount']._serialized_options = b'\310\336\037\000'
  _globals['_COLLATERALBALANCE']._serialized_start=125
  _globals['_COLLATERALBALANCE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
