# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/collateral/genesis.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from inference.collateral import params_pb2 as inference_dot_collateral_dot_params__pb2
from inference.collateral import collateral_balance_pb2 as inference_dot_collateral_dot_collateral__balance__pb2
from inference.collateral import unbonding_pb2 as inference_dot_collateral_dot_unbonding__pb2
from inference.collateral import jailed_pb2 as inference_dot_collateral_dot_jailed__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"inference/collateral/genesis.proto\x12\x14inference.collateral\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a!inference/collateral/params.proto\x1a-inference/collateral/collateral_balance.proto\x1a$inference/collateral/unbonding.proto\x1a!inference/collateral/jailed.proto\"\x84\x03\n\x0cGenesisState\x12?\n\x06params\x18\x01 \x01(\x0b\x32\x1c.inference.collateral.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12\x65\n\x17\x63ollateral_balance_list\x18\x02 \x03(\x0b\x32\'.inference.collateral.CollateralBalanceB\x04\xc8\xde\x1f\x00R\x15\x63ollateralBalanceList\x12k\n\x19unbonding_collateral_list\x18\x03 \x03(\x0b\x32).inference.collateral.UnbondingCollateralB\x04\xc8\xde\x1f\x00R\x17unbondingCollateralList\x12_\n\x17jailed_participant_list\x18\x04 \x03(\x0b\x32\'.inference.collateral.JailedParticipantR\x15jailedParticipantListB8Z6github.com/productscience/inference/x/collateral/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.collateral.genesis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/productscience/inference/x/collateral/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['collateral_balance_list']._options = None
  _globals['_GENESISSTATE'].fields_by_name['collateral_balance_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['unbonding_collateral_list']._options = None
  _globals['_GENESISSTATE'].fields_by_name['unbonding_collateral_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=257
  _globals['_GENESISSTATE']._serialized_end=645
# @@protoc_insertion_point(module_scope)
